name: api-rpc-factom
version: '0.1.3.5'
description: simple json-rpc API client for Factom blockchain
synopsis: simple json-rpc API client for Factom
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! 'Copyright: (c) 2019-2020 Sergey Bushnyak, Kompendium, LLC'
license: MIT
github: kompendium-ano/factom-haskell-client
extra-source-files:
- README.md
dependencies:
- bytestring
library:
  source-dirs: src
  exposed-modules:
  - Factom.RPC.Api
  - Factom.RPC.Wallet.Api
  - Factom.RPC.Types
  dependencies:
  - base >=4.7 && <5
  - aeson
  - aeson-casing
  - text
  - time
  - http-conduit
  - http-client
  - http-client-tls
  - network
  - transformers
  - remote-monad
  - remote-json
  - remote-json-client
  - json-alt
executables:
  factom-app:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - http-conduit
    - http-client
    - aeson
    - stm
    - text
    - time
    - api-rpc-factom
tests:
  factom-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - api-rpc-factom
